"""
APIRecon - Postman Collection Security Analysis Report Generator
Generates a professional cybersecurity assessment PDF using ReportLab.
"""

import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    BaseDocTemplate,
    PageTemplate,
    Frame,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    PageBreak,
    NextPageTemplate,
)

# ---------------------------------------------------------------------------
# Constants / Theme
# ---------------------------------------------------------------------------

CYAN = colors.HexColor("#0891B2")
DARK_CYAN = colors.HexColor("#0E7490")
BLACK = colors.black
WHITE = colors.white
LIGHT_GRAY = colors.HexColor("#F1F5F9")
MED_GRAY = colors.HexColor("#E2E8F0")
BORDER_GRAY = colors.HexColor("#94A3B8")

SEVERITY_COLORS = {
    "HIGH": colors.HexColor("#DC2626"),
    "MEDIUM": colors.HexColor("#EA580C"),
    "LOW": colors.HexColor("#16A34A"),
}

PAGE_SIZE = letter
LANDSCAPE_PAGE_SIZE = landscape(letter)
MARGIN = 0.6 * inch

FOOTER_TEXT = "Generated by APIRecon"

styles = getSampleStyleSheet()

TITLE_STYLE = ParagraphStyle(
    "CoverTitle",
    parent=styles["Title"],
    fontName="Helvetica-Bold",
    fontSize=30,
    textColor=CYAN,
    alignment=TA_CENTER,
    spaceAfter=6,
)

SUBTITLE_STYLE = ParagraphStyle(
    "CoverSubtitle",
    parent=styles["Normal"],
    fontName="Helvetica",
    fontSize=14,
    textColor=BLACK,
    alignment=TA_CENTER,
    spaceAfter=6,
)

COVER_META_STYLE = ParagraphStyle(
    "CoverMeta",
    parent=styles["Normal"],
    fontName="Helvetica",
    fontSize=11,
    textColor=BLACK,
    alignment=TA_CENTER,
    spaceAfter=4,
)

SECTION_TITLE_STYLE = ParagraphStyle(
    "SectionTitle",
    parent=styles["Heading2"],
    fontName="Helvetica-Bold",
    fontSize=15,
    textColor=WHITE,
    backColor=CYAN,
    borderPadding=(6, 6, 6, 6),
    leftIndent=0,
    spaceBefore=0,
    spaceAfter=10,
)

BODY_STYLE = ParagraphStyle(
    "BodyCell",
    parent=styles["Normal"],
    fontName="Helvetica",
    fontSize=8.5,
    textColor=BLACK,
    leading=11,
)

HEADER_CELL_STYLE = ParagraphStyle(
    "HeaderCell",
    parent=styles["Normal"],
    fontName="Helvetica-Bold",
    fontSize=9,
    textColor=WHITE,
    leading=12,
    alignment=TA_LEFT,
)

EMPTY_STYLE = ParagraphStyle(
    "EmptyNotice",
    parent=styles["Normal"],
    fontName="Helvetica",
    fontSize=10,
    textColor=colors.HexColor("#64748B"),
    spaceBefore=2,
    spaceAfter=12,
)


# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------

def _cell(value):
    """Wrap a raw value in a Paragraph so long text wraps correctly in tables."""
    if value is None:
        value = ""
    text = str(value)
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return Paragraph(text, BODY_STYLE)


def _header_cell(value):
    text = str(value).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return Paragraph(text, HEADER_CELL_STYLE)


def add_section_title(elements, title):
    """Append a styled cyan section header to the elements list."""
    elements.append(Paragraph(f"&nbsp;&nbsp;{title}", SECTION_TITLE_STYLE))
    elements.append(Spacer(1, 8))


def add_empty_notice(elements, message):
    elements.append(Paragraph(message, EMPTY_STYLE))


def create_table(header_row, data_rows, col_widths=None, row_text_colors=None):
    """
    Build a styled ReportLab Table.

    header_row: list of column header strings
    data_rows: list of lists (raw values, will be wrapped in Paragraphs)
    col_widths: optional list of column widths
    row_text_colors: optional list (len == len(data_rows)) of dicts
                      {col_index: color} to override text color per cell
                      (used for severity color coding)
    """
    table_data = [[_header_cell(h) for h in header_row]]

    for row_idx, row in enumerate(data_rows):
        rendered_row = []
        for col_idx, value in enumerate(row):
            override = None
            if row_text_colors and row_idx < len(row_text_colors):
                override = row_text_colors[row_idx].get(col_idx)
            if override is not None:
                style = ParagraphStyle(
                    f"cell_{row_idx}_{col_idx}",
                    parent=BODY_STYLE,
                    textColor=override,
                    fontName="Helvetica-Bold",
                )
                text = str(value) if value is not None else ""
                text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                rendered_row.append(Paragraph(text, style))
            else:
                rendered_row.append(_cell(value))
        table_data.append(rendered_row)

    table = Table(table_data, colWidths=col_widths, repeatRows=1)

    style_commands = [
        ("BACKGROUND", (0, 0), (-1, 0), CYAN),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, 0), 8),
        ("GRID", (0, 0), (-1, -1), 0.75, BORDER_GRAY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 1), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 5),
    ]

    for i in range(1, len(table_data)):
        bg = LIGHT_GRAY if i % 2 == 1 else WHITE
        style_commands.append(("BACKGROUND", (0, i), (-1, i), bg))

    table.setStyle(TableStyle(style_commands))
    return table


def add_footer(canvas, doc):
    """onPage callback: draws footer text + 'Page X' on every page."""
    canvas.saveState()
    page_width = doc.pagesize[0]

    canvas.setStrokeColor(BORDER_GRAY)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.55 * inch, page_width - MARGIN, 0.55 * inch)

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#475569"))
    canvas.drawString(MARGIN, 0.35 * inch, FOOTER_TEXT)
    canvas.drawRightString(page_width - MARGIN, 0.35 * inch, f"Page {canvas.getPageNumber()}")
    canvas.restoreState()


# ---------------------------------------------------------------------------
# Data access helpers (defensive against missing/odd keys)
# ---------------------------------------------------------------------------

def _safe_get(d, key, default=None):
    if not isinstance(d, dict):
        return default
    return d.get(key, default)


def _variables_rows(variables):
    """Normalize the 'variables' section into a list of (key, value) rows."""
    if not variables:
        return []
    if isinstance(variables, dict):
        if "items" in variables and isinstance(variables["items"], list):
            rows = []
            for item in variables["items"]:
                if isinstance(item, dict):
                    rows.append([item.get("key", ""), item.get("value", "")])
            return rows
        # Flat dict of key -> value
        return [[k, v] for k, v in variables.items()]
    if isinstance(variables, list):
        rows = []
        for item in variables:
            if isinstance(item, dict):
                rows.append([item.get("key", ""), item.get("value", "")])
        return rows
    return []


def _variables_count(variables):
    if not variables:
        return 0
    if isinstance(variables, dict):
        if "count" in variables:
            return variables.get("count", 0)
        if "items" in variables and isinstance(variables["items"], list):
            return len(variables["items"])
        return len(variables)
    if isinstance(variables, list):
        return len(variables)
    return 0


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def generate_report(analysis):
    if not isinstance(analysis, dict):
        analysis = {}

    collection = _safe_get(analysis, "collection", {}) or {}
    summary = _safe_get(analysis, "summary", {}) or {}
    methods = _safe_get(analysis, "methods", {}) or {}
    authentication = _safe_get(analysis, "authentication", {}) or {}
    variables = _safe_get(analysis, "variables", {}) or {}
    endpoints = _safe_get(analysis, "endpoints", []) or []
    headers = _safe_get(analysis, "headers", {}) or {}
    query_parameters = _safe_get(analysis, "query_parameters", {}) or {}
    sensitive_data = _safe_get(analysis, "sensitive_data", []) or []
    response = _safe_get(analysis, "response", []) or []

    collection_name = collection.get("name", "Unknown Collection")
    generated_dt = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    total_requests = summary.get("total_requests", 0)
    total_folders = summary.get("total_folders", 0)
    total_variables = summary.get("total_variables", _variables_count(variables))
    total_sensitive_findings = summary.get(
        "total_sensitive_findings", len(sensitive_data)
    )
    total_endpoints = summary.get("total_endpoints", len(endpoints))

    # -----------------------------------------------------------------
    # Document + page templates (portrait + landscape, both footer-aware)
    # -----------------------------------------------------------------

    doc = BaseDocTemplate(
        "APIRecon_Report.pdf",
        pagesize=PAGE_SIZE,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
        title="APIRecon Security Analysis Report",
        author="APIRecon",
    )

    portrait_frame = Frame(
        MARGIN, MARGIN,
        PAGE_SIZE[0] - 2 * MARGIN,
        PAGE_SIZE[1] - 2 * MARGIN,
        id="portrait_frame",
    )

    landscape_frame = Frame(
        MARGIN, MARGIN,
        LANDSCAPE_PAGE_SIZE[0] - 2 * MARGIN,
        LANDSCAPE_PAGE_SIZE[1] - 2 * MARGIN,
        id="landscape_frame",
    )

    portrait_template = PageTemplate(
        id="Portrait",
        frames=[portrait_frame],
        onPage=add_footer,
        pagesize=PAGE_SIZE,
    )

    landscape_template = PageTemplate(
        id="Landscape",
        frames=[landscape_frame],
        onPage=add_footer,
        pagesize=LANDSCAPE_PAGE_SIZE,
    )

    doc.addPageTemplates([portrait_template, landscape_template])

    elements = []

    # -----------------------------------------------------------------
    # Cover page
    # -----------------------------------------------------------------

    elements.append(Spacer(1, 1.8 * inch))
    elements.append(Paragraph("APIRecon", TITLE_STYLE))
    elements.append(Paragraph("Postman Collection Security Analysis Report", SUBTITLE_STYLE))
    elements.append(Spacer(1, 0.6 * inch))
    elements.append(Paragraph(f"Collection Name: {collection_name}", COVER_META_STYLE))
    elements.append(Paragraph(f"Generated: {generated_dt}", COVER_META_STYLE))
    elements.append(Spacer(1, 1 * inch))
    elements.append(PageBreak())

    # -----------------------------------------------------------------
    # Executive Summary
    # -----------------------------------------------------------------

    add_section_title(elements, "Executive Summary")
    summary_rows = [
        ["Total Requests", total_requests],
        ["Total Folders", total_folders],
        ["Total Variables", total_variables],
        ["Total Sensitive Findings", total_sensitive_findings],
        ["Total Endpoints", total_endpoints],
    ]
    elements.append(
        create_table(
            ["Metric", "Value"],
            summary_rows,
            col_widths=[3.5 * inch, 2.5 * inch],
        )
    )
    elements.append(Spacer(1, 16))

    # -----------------------------------------------------------------
    # Methods
    # -----------------------------------------------------------------

    add_section_title(elements, "HTTP Methods")
    if methods:
        rows = [[m, c] for m, c in methods.items()]
        elements.append(create_table(["Method", "Count"], rows, col_widths=[3.5 * inch, 2.5 * inch]))
    else:
        add_empty_notice(elements, "No Methods Found")
    elements.append(Spacer(1, 16))

    # -----------------------------------------------------------------
    # Authentication
    # -----------------------------------------------------------------

    add_section_title(elements, "Authentication")
    if authentication:
        rows = [[a, c] for a, c in authentication.items()]
        elements.append(create_table(["Auth Type", "Count"], rows, col_widths=[3.5 * inch, 2.5 * inch]))
    else:
        add_empty_notice(elements, "No Authentication Data Found")
    elements.append(Spacer(1, 16))

    # -----------------------------------------------------------------
    # Variables
    # -----------------------------------------------------------------

    add_section_title(elements, "Variables")
    var_rows = _variables_rows(variables)
    if var_rows:
        elements.append(create_table(["Key", "Value"], var_rows, col_widths=[3 * inch, 3 * inch]))
    else:
        add_empty_notice(elements, "No Variables Found")
    elements.append(Spacer(1, 16))

    # -----------------------------------------------------------------
    # Headers
    # -----------------------------------------------------------------

    add_section_title(elements, "Headers")
    if headers:
        rows = [[h, c] for h, c in headers.items()]
        elements.append(create_table(["Header", "Count"], rows, col_widths=[3.5 * inch, 2.5 * inch]))
    else:
        add_empty_notice(elements, "No Headers Found")
    elements.append(Spacer(1, 16))

    # -----------------------------------------------------------------
    # Query Parameters
    # -----------------------------------------------------------------

    add_section_title(elements, "Query Parameters")
    if query_parameters:
        rows = [[q, c] for q, c in query_parameters.items()]
        elements.append(create_table(["Parameter", "Count"], rows, col_widths=[3.5 * inch, 2.5 * inch]))
    else:
        add_empty_notice(elements, "No Query Parameters Found")
    elements.append(Spacer(1, 16))

    # -----------------------------------------------------------------
    # Sensitive Data (color coded by severity)
    # -----------------------------------------------------------------

    add_section_title(elements, "Sensitive Data Findings")
    if sensitive_data:
        rows = []
        row_colors = []
        for finding in sensitive_data:
            if not isinstance(finding, dict):
                continue
            severity_raw = str(finding.get("severity", "")).upper().strip()
            rows.append([
                finding.get("key", ""),
                severity_raw or "UNKNOWN",
                finding.get("location", ""),
                finding.get("method", ""),
                finding.get("endpoint", ""),
            ])
            color = SEVERITY_COLORS.get(severity_raw)
            row_colors.append({1: color} if color else {})

        elements.append(
            create_table(
                ["Key", "Severity", "Location", "Method", "Endpoint"],
                rows,
                col_widths=[1.1 * inch, 0.9 * inch, 1.3 * inch, 0.8 * inch, 1.9 * inch],
                row_text_colors=row_colors,
            )
        )
    else:
        add_empty_notice(elements, "No Sensitive Data Found")
    elements.append(Spacer(1, 16))

    # -----------------------------------------------------------------
    # Response
    # -----------------------------------------------------------------

    add_section_title(elements, "Responses")
    if response:
        rows = []
        for r in response:
            if isinstance(r, dict):
                rows.append([r.get("status", ""), r.get("code", "")])
        if rows:
            elements.append(create_table(["Status", "Code"], rows, col_widths=[3.5 * inch, 2.5 * inch]))
        else:
            add_empty_notice(elements, "No Responses Found")
    else:
        add_empty_notice(elements, "No Responses Found")
    elements.append(Spacer(1, 16))

    # -----------------------------------------------------------------
    # Endpoints (landscape page)
    # -----------------------------------------------------------------

    elements.append(NextPageTemplate("Landscape"))
    elements.append(PageBreak())
    add_section_title(elements, "Endpoints")
    if endpoints:
        rows = []
        for ep in endpoints:
            if isinstance(ep, dict):
                rows.append([
                    ep.get("method", ""),
                    ep.get("url", ""),
                    ep.get("auth", ""),
                ])
        if rows:
            elements.append(
                create_table(
                    ["Method", "URL", "Auth"],
                    rows,
                    col_widths=[1.2 * inch, 6.5 * inch, 1.8 * inch],
                )
            )
        else:
            add_empty_notice(elements, "No Endpoints Found")
    else:
        add_empty_notice(elements, "No Endpoints Found")

    elements.append(NextPageTemplate("Portrait"))

    # -----------------------------------------------------------------
    # Build
    # -----------------------------------------------------------------

    doc.build(elements)


if __name__ == "__main__":
    sample_analysis = {
        "collection": {"name": "Sample API Collection", "schema": "v2.1.0", "postman_id": "abc-123"},
        "summary": {"total_requests": 42, "total_folders": 6},
        "methods": {"GET": 20, "POST": 15, "DELETE": 4, "PUT": 3},
        "authentication": {"Bearer Token": 30, "API Key": 8, "None": 4},
        "variables": {"count": 2, "items": [{"key": "base_url", "value": "https://api.example.com"}, {"key": "token", "value": "***redacted***"}]},
        "endpoints": [
            {"method": "GET", "url": "https://api.example.com/v1/users/{id}/profile/settings/notifications", "auth": "Bearer"},
            {"method": "POST", "url": "https://api.example.com/v1/auth/login", "auth": "None"},
        ],
        "headers": {"Content-Type": 42, "Authorization": 30},
        "query_parameters": {"page": 12, "limit": 12},
        "sensitive_data": [
            {"key": "api_key", "severity": "HIGH", "location": "Header", "method": "GET", "endpoint": "/v1/users"},
            {"key": "session_id", "severity": "MEDIUM", "location": "Cookie", "method": "POST", "endpoint": "/v1/auth/login"},
            {"key": "debug_flag", "severity": "LOW", "location": "Query Param", "method": "GET", "endpoint": "/v1/status"},
        ],
        "response": [{"status": "OK", "code": 200}, {"status": "Unauthorized", "code": 401}],
    }
    generate_report(sample_analysis) 
    print("Generated APIRecon_Report.pdf")